### PR TITLE
Added support for several exchanges and fiat currencies, also small fix for default history export filename

### PR DESCRIPTION
**Pull request by PaulBirchDev**
Added support for CoinFloor public API ticker call for GBP fiat FX

### CODE REVIEW

**Comment by Danconnolly** [comment]
looks good.

**Comment by PaulBirchDev** [comment]
Cheers - I ran out of time so just did the GBP (it took me a while to get the dev version built on my mac). Hopefully I'll get the time to add a few more exchanges and currencies (always good to have a choice in case one goes offline or something).

**Comment by PaulBirchDev** [comment]
Got a bit more time today so added extra support for Cex.io exchange.

**Comment by PaulBirchDev** [comment]
Fixed a small issue with the default history file being named wrong - issue #270 - but I couldn't replicate the second problem - works fine for me on my mac (changing filename, directory or both).

**Comment by fyookball** [comment]
@PaulBirchDev did we get fiat for Android?  People are requesting it a lot.  willing to pay a bounty.

**Comment by PaulBirchDev** [comment]
I didn't put anything in specifically for Android but I just copied some of the standard routines to extend support for other exchanges/pairs. Provided the standard code works with Android - the new ones should work. I don't have an android device so can't really test it myself.

Also #300 - was added recently by @gwestwood to add even more (needs reviewing).

**Comment by fyookball** [comment]
@PaulBirchDev no the entire fiat functionality is missing on android.

**Comment by fyookball** [comment]
@PaulBirchDev are you an iphone guy?

**Comment by PaulBirchDev** [comment]
Ahh I didn't realise that - I generally work on PC/Mac and occasionally do some iOS development. (yep use an iPhone normally). I might be able to spin up an Android Dev environment and have a look, problem is getting the time to do it, :)

**Comment by fyookball** [comment]
people have been requesting iOS version.  if thats something you are interested in, let me know. bounties available.

**Comment by PaulBirchDev** [comment]
I've installed Android Studio 3, installed various dependencies etc. Now I've been able to build the electron cash PythonUtil.Class in the out folder. I then run the make_apk.. and here I hit problems. I've got rid of all but a final issue, but I'm not sure what the actual problem is.. the error is:

/Users/paulbirch/.buildozer/android/platform/android-ndk-r9c/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: jpeg: malformed archive header name at 8
collect2: error: ld returned 1 exit status
error: command 'arm-linux-androideabi-gcc' failed with exit status 1

Any ideas?

**Comment by fyookball** [comment]
did you run make theming first

**Comment by PaulBirchDev** [comment]
Ahh no... and running that fails as it can't find kivy, hmm I thought I had that installed.. okay I'll keep digging!

**Comment by PaulBirchDev** [comment]
Okay - kivy now installed, make theming runs fine and creates the atlas file. But the make_apk is still failing..

I'll keep plugging away when I get time but if you have any ideas - full log is attached.
[make_apk.txt](https://github.com/fyookball/electrum/files/1523719/make_apk.txt)

**Comment by fyookball** [comment]
hmm. dont forget to delete dot buildozer folder each time you rebuild

**Comment by PaulBirchDev** [comment]
I've tried that - it doesn't help. I've made a change to the name of the package in the Buildozer.spec file to remove the hyphen and it is much happier. In fact the APK builds now. But I get one more error, I'm presuming that this is stopping the APK being deployed and run? 

```
[DEBUG]:   	BUILD SUCCESSFUL
[DEBUG]:   	Total time: 3 seconds
[INFO]:    <- directory context /Users/paulbirch/DevProjects/sources/python-for-android-master
[INFO]:    # Copying APK to current directory
[INFO]:    # Found APK file: /Users/paulbirch/DevProjects/electrum-electronCash/.buildozer/android/platform/build/dists/ElectronCash/bin/Electron-Cash-2.8.2-debug.apk
[DEBUG]:   -> running cp /Users/paulbirch/DevProjects/electrum-electronCash/.buildozer/android/platform/build/dists/ElectronCash/bin/Electron-Cash-2.8.2-debug.apk ./
WARNING: Received a --sdk argument, but this argument is deprecated and does nothing.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/buildozer", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/scripts/client.py", line 13, in main
    Buildozer().run_command(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/__init__.py", line 1058, in run_command
    self.target.run_commands(args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/target.py", line 91, in run_commands
    func(args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/target.py", line 103, in cmd_debug
    self.buildozer.build()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/__init__.py", line 212, in build
    self.target.build_package()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/buildozer/targets/android.py", line 808, in build_package
    copyfile(join(apk_dir, apk), join(self.buildozer.bin_dir, apk_dest))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/paulbirch/DevProjects/electrum-electronCash/.buildozer/android/platform/build/dists/ElectronCash/build/outputs/apk/ElectronCash-debug.apk'
make: [apk] Error 1 (ignored)
# Cleaning up
# rename main.py to electrum
# remove buildozer.spec
```

It looks like the file copy is failing it seems to be the destination folder it is having a problem with - the APK is there in the source folder.

**Comment by fyookball** [comment]
should work. grab it rfrom there

**Comment by PaulBirchDev** [comment]
I've just dragged and dropped it into the simulator - it is currently on "Installing APK" - has been there for a while. How long does it normally take?

**Comment by fyookball** [comment]
couple seconds

**Comment by PaulBirchDev** [comment]
Hmm - this has been running for minutes now and nothing seems to be happening, no errors or anything. I've cancelled it and kicked off the install again but it seems to be doing the same thing.

**Comment by fyookball** [comment]
usually when there is an issue , the way to debug on an android device is with adb

**Comment by PaulBirchDev** [comment]
Okay a bit further forward! - I've had a look at Android monitor when the install starts it shows a PackageInstaller error - Failed to extract native libraries -113. It seems that it is due to the simulator running on x86 and the APK compiling for ARM7. As I don't have an actual Android device I'm not sure if I can progress here as looking at the docs for buildozer I can't see a way of generating an APK which will run on both ARM7 or x86. Unless I can somehow make the simulator run as an actual ARM7 CPU.

**Comment by fyookball** [comment]
lol ok.   what about iOS dev?

**Comment by PaulBirchDev** [comment]
Well I got the simulator up and running and I even managed to install the APK file (but the simulator keeps crashing and going SUPER slow, as it is running in ARM7 mode). I've not managed to get Electron Cash to start, I click on it and the splash screen shows up and then usually the simulator throws another error so I've no idea if the problem is with the APK file or the simulator.

When I get a bit of time I'm going to build a simple python/kivy project and see if I can make an IOS app - as apparently you can do this with buildozer. If I can get that running and deploy it to my iPhone I'll have a look to see what is involved with making Electron Cash work... I can't promise anything at the moment but I'll have a look into it. :)

**Comment by fyookball** [comment]
sounds good. again, we can pay a generous bounty for this.

**Pull request merged**
