### PR TITLE
Trezor support

### PR DESCRIPTION
**Pull request by jhoenicke**
This patch contains the minimal changes to get electron cash running with Trezor (firmware 1.5.1).  The patches are cherry-picked from Saleem Rashid's electrum-cash branch.

### CODE REVIEW

**Comment by dabura667** [comment]
ACK

**Comment by prusnak** [comment]
:+1:

**Comment by dabura667** [comment]
Only thing I would change is "Bcash."

The rest of the app uses "Bitcoin Cash."

Consistency is good.

**Comment by prusnak** [comment]
You need to keep the string "Bcash", because that is how TREZOR knows you want to use Bcash/Bitcoin Cash. (This string is being sent in the message via USB).

**Comment by jhoenicke** [comment]
Yes, also note that this string is never displayed to the user. It is just the identifier for the coin used by the TREZOR firmware.

**Comment by weissjeffm** [comment]
When I run this branch, I get 

```
Traceback (most recent call last):
  File "/home/jweiss/workspace/electrum/gui/qt/util.py", line 582, in run
    result = task.task()
  File "/home/jweiss/workspace/electrum/lib/wallet.py", line 1103, in sign_transaction
    k.sign_transaction(tx, password)
  File "/home/jweiss/workspace/electrum/plugins/trezor/plugin.py", line 66, in sign_transaction
    self.plugin.sign_transaction(self, tx, prev_tx, xpub_path)
  File "/home/jweiss/workspace/electrum/plugins/trezor/plugin.py", line 240, in sign_transaction
    inputs = self.tx_inputs(tx, True)
  File "/home/jweiss/workspace/electrum/plugins/trezor/plugin.py", line 307, in tx_inputs
    txinputtype.amount = txin['value']
AttributeError: 'TxInputType' object has no attribute 'amount'
```

**Comment by prusnak** [comment]
You need to have latest stable python-trezor (currently 0.7.16)

**Comment by dabura667** [comment]
@prusnak @jhoenicke looks like Trezor is adding an extra sighash to the signatures.

Perhaps a multisig only problem?

See #47

**Pull request merged**
