### PR TITLE
Rename python packages from electrum to electroncash

### LINKED ISSUE #8: Electron Cash uses "electrum" Python package name
So it cannot be installed system-wide along with Electrum proper.

### PR DESCRIPTION
**Pull request by moreati**
This change renames the Python packages as follows

| Old name | New name |
|---------------|----------------|
|electrum_gui|electroncash_gui|
|electrum_plugins|electroncash_plugins|
|electrum|electroncash|

The following attribute, class, and method names were consciously _not_ changed (for now):

1. `electroncash_gui.kivy.ElectrumGui`
1. `electroncash_gui.kivy.main_window.ElectrumWindow`
1. `electroncash_gui.kivy.main_window.ElectrumWindow.electrum_config`
1. `electroncash_gui.qt.ElectrumGui`
1. `electroncash_gui.qt.main_window.ElectrumWindow`
1. `electroncash_gui.stdio.ElectrumGui`
1. `electroncash_gui.text.ElectrumGui`
1. `electroncash_plugins.ledger.ledger...get_client_electrum()`
1. `electroncash_plugins.trezor.plugin...electrum_tx_to_txtype()`
1. `electroncash.simple_config.SimpleConfig.electrum_path`
1. `electroncash.websockets.ElectrumWebSocket`
1. `electroncash.version.ELECTRUM_VERSION`

Fixes #8

### CODE REVIEW

**Comment by moreati** [comment]
As a rough measure, this PR reduces the number of occurrences of the 'electrum' in the code base from 757 to 452. As measured using

```sh
ag -i -c electrum | cut -d: -f 2 | awk '{s+=$1} END {printf "%.0f\n", s}'
```

**Comment by moreati** [comment]
Review notes: The first 3 commits are 100% mechanistic. I believe the 4th commit will need the closest scrutiny.

**Comment by fyookball** [comment]
im having a look

**Comment by kyuupichan** [comment]
Hey, thanks for this.  Can you update to fix the conflict?  I think we should consider merging this soon.

**Comment by kyuupichan** [comment]
Never mind, I've fixed it locally.  I think this looks good so I'll merge it.

**Pull request merged**
