### PR TITLE
Fixups for macOS -- get rid of cruft and 1 tiny nit in osx.spec

### PR DESCRIPTION
**Pull request by cculianu**

### CODE REVIEW

**Comment by marceloneil** [comment]
Do you think you can squash these commits?

**Comment by cculianu** [comment]
Sure!  I have no idea got to do that though.  Do you know  offhand how to do that and not destroy my repository?

**Comment by marceloneil** [comment]
I think `git rebase --autosquash -I <commit hash>` with the commit hash being the oldest you want to squash.

**Comment by marceloneil** [comment]
Oh no! What happened

**Pull request closed without merging**
