### PR TITLE
Fee slider modifications and messaging as discussed in Slack on 7/4/18

### PR DESCRIPTION
**Pull request by cculianu**
What's new:

If "Custom Fee Rate" is specified in preferences then:

1. Fee slider disappears
2. It's replaced by a label (well, a HelpLabel actually) that shows the fee rate as calculated from the custom fee rate and/or manual fee override (manual fee override wins, but the custom fee rate is the initial default)

If "Custom Fee Rate" is not specified in preferences (this is the default on new installs), then:

1. Fee slider is visible and works as normal
2. The aforementioned help label is always hidden.

- Note that I also cleaned up Jonald's code from the last commit and refactored it, and also made it play nice with the esoteric "CPFP" dialog which you can get from an unconfirmed tx, if you right-click on it in "history" and do "Child pays for parent"

### CODE REVIEW

**Comment by marceloneil** [comment]
Do you have any screenshots for a lazy person that doesn't want to run your PR :wink:?

**Comment by cculianu** [comment]
Yes.. hang tight .. will post some.

**Comment by cculianu** [comment]
Default screen (custom fees enabled, set to 1000): 
screen shot 2018-07-04 at 9 09 25 pm
Custom fees enabled, tx is partially filled in, real effective fee rate is updated in the label (also shows the help text copy I decided to use):
screen shot 2018-07-04 at 9 09 45 pm
I updated the fee manually.. note the Fee label updated itself correctly:
screen shot 2018-07-04 at 9 10 00 pm
Disabling the "custom fee rate" in prefs immediately swaps back the "FeeSlider" and hides the QLabel:
screen shot 2018-07-04 at 9 10 12 pm
Fee slider works perfectly as before we added this facility.
screen shot 2018-07-04 at 9 10 32 pm

**Comment by marceloneil** [comment]
On the first screenshot, maybe the "total fee" box should be auto-filled in? Not huge, but thats my 2 cents.

**Comment by cculianu** [comment]
Marcel -- yeah the existing "update fee" code in main_window.py decided not to fill anything in until the "amount" is specified. 

They do this because it's not clear what the TX size will be until at least "amount" is specified (since it's not clear how many inputs will be gobbled up for the TX).

We *could* pre-fill it in by having the "fake-tx" code actually implicitly create a dummy tx of '0' amount... to pre-fill that manual fee rate box..

If you guys want that, I will do that as a separate PR...

**Comment by marceloneil** [comment]
Let's not over-complicate things I guess, but maybe keep that in mind for the future? We can create an issue if it's something we want

**Comment by cculianu** [comment]
I agree with that. :)

**Comment by hegjon** [comment]
Fees are so 2017, no users need control over that in 2018

**Comment by cculianu** [comment]
I actually agree.. i think we should make the default such that 

"Custom fee rate" = 1.0 sats/B

(which hides the slider, and just does the intelligent thing)

That's what I would do if it were up to.

**Comment by kyuupichan** [comment]
@cculianu FWIW I agree re 1 sat/byte as default custom fee rate

**Comment by fyookball** [comment]
looks good overall, its an improvement over previous. we can keep improving if necessary.

**Pull request merged**
