### PR TITLE
Change the wallet copy function from `shutil.copy2` to `shutil.copyfile`

### PR DESCRIPTION
**Pull request by alexander255**
After the “tremendos response” to #665, I'm just gonna propose the change mentioned in that issue for merging. If you have any objections please say so, otherwise I think it really won't hurt to have this in *Electron-Cash*.

### CODE REVIEW

**Comment by rt121212121** [comment]
Is it possible to detect flatpak, and conditionally use `copyfile()` in that case?

**Comment by alexander255** [comment]
Yes, but is there any good reason why this should be done? What's the benifit of copying file attributes in this function?

**Comment by rt121212121** [comment]
Why not preserve the information if it is there?  It's not my call, but I
would be wary of throwing it away as not important to anyone, because a
more abstract system finds it inconvenient.  Better if it is feasible to
support the lesser way on the lesser system as well IMO.

**Comment by cculianu** [comment]
FWIW I agree that "save wallet" is more like an exporting function.  And you want to export the file, just the file, and not its permissions or anything else.

I work on the iOS branch of this project (to be released soon!), so I'm not the authority here.

But if you need my vote of confidence -- I'm all in favor of switching it over.  It's low-risk and not sure why it was there in the first place that way.  If you have justification for changing it I don't see why not.

Also.. I use copy2 in my iOS just because of paranoia (wanted to copy it exactly) -- but maybe I should switch back to copyfile. Hmm.

**Comment by marceloneil** [comment]
Paging @kyuupichan

**Pull request merged**
