### PR TITLE
Added working testnet server.

### PR DESCRIPTION
**Pull request by ser**
None of listed testnet servers work. I created my own one with intention for long term public use, as I need it for development.

### CODE REVIEW

**Comment by marceloneil** [comment]
Hmm that's odd, some of the servers were working for me last time I checked, albeit the black headers sync was pretty brutal

**Comment by ser** [comment]
So maybe writing comments just check?

**Comment by marceloneil** [comment]
I can't test this as I'm out of town btw

**Comment by ser** [comment]
But you have your say being out of town. It's more than 10 days I am unable to use testnet, I had no other choice than creating my own server. There's one server responding but it does not have current chain.

**Comment by marceloneil** [comment]
I know @molecular runs one of the testnet servers, you might need to do some digging for the other one if you want them to fix it

**Comment by ser** [comment]
I'll not try to convince anyone to do what they don't want to do, apparently. 

I found another list of running servers, none of them are listed in the wallet:

https://1209k.com/bitcoin-eye/ele.php?chain=tbch

**Comment by molecular** [comment]
regarding the criptolayer electrumx servers: need to upgrade my electrumx instances (server side disconnects saying "unsupported protocol version request 1.2") , but that requires python 2->3 upgrade which I can't easily do on that system... so it'll be a while before they're operational again (due to time constraints).

**Comment by kyuupichan** [comment]
@molecular yeah please keep close to recent ElectrumX versions.  There are protocol changes I'm trying to push through that will help for future scaling and also the internal code if anyone looks into improving it.  There are more to come in the future too.

**Comment by kyuupichan** [comment]
@molecular ElectrumX has never been Python2 so not sure what you're referrring to

**Comment by molecular** [comment]
@kyuupichan ah, sorry, yeah. I was confused... it's been a while. There was some reason I couldn't upgrade python3 to 3.6 and I think newer versions of electrumx need that, no? Stuck on 3.5.3 for now... looks like I'm looking at an upgrade orgy soon.

**Comment by cculianu** [comment]
( ͡° ͜ʖ ͡°)

**Comment by kyuupichan** [comment]
@molecular yeah.  We could do with more servers running the very latest code.  This week I'll probably release version 1.6 which will have improved RPC methods that will allow Electron Cash to not download 45 MB of header data on initial start, but we can't update the client until more servers are running that codel

**Comment by molecular** [comment]
@kyuupichan ok, so newest debian stable still has only python 3.5.3 as newest python3 version :-( electrumx requires 3.6 (since uses at least one new feature introduced in 3.6: "formatted string literals" (wow! nice feature)). So I'm compiling python 3.6.4... (took a while)...

So my 4 criptolayer.net servers (core/cash, mainnet/testnet) are running electrumx 1.5.2 now. (core mainnet has db problems "Scanning for excess history flushes...", but I don't care much tbh)

Thanks for the kick in the butt.

**Comment by molecular** [comment]
@ser: I know it's probably a bit late now, but my testnet electrumx instance should be up to date now (electrum-testnet-abc.criptolayer.net port 50112 ssl). Works with my (probably dated) electron-cash 3.3.

**Comment by kyuupichan** [comment]
@molecular I just released 1.6pre1 which includes protocol upgrades that will permit the client to not need to download all the headers (not yet implemented client-side).  Can you upgrade to that?  It's hard to push changes client-side if no servers are running the server-side code.  Thanks!

**Comment by molecular** [comment]
@kyuupichan upgraded all 4 instances to 1.6pre1

thanks for your awesome work, btw!

**Comment by kyuupichan** [comment]
@molecular if you could update to 1.6pre3 it would be great; it's a release candidate for 1.6 now.  I've done a massive refactoring.  Where do you hang out so we can communicate?  Here isn't great.

**Comment by ser** [comment]
I've upgraded to current master either, have two peers working, electrum-testnet-abc.criptolayer.net and bch0.kister.net

**Comment by molecular** [comment]
@kyuupichan I currently "hang out" mainly in the real world. Suggest a place and I'll drop by. bchchat slack maybe, or bitcoinabc slack? I'm not up to date on where people hang out.

**Comment by kyuupichan** [comment]
@molecular great, I'm on both.  I should perhaps start a mail list for those running servers where I send occasional updates, or something...

**Comment by ser** [comment]
@kyuupichan and official active list of electrum servers (auto-monitored) which i volunteer to code, host and maintain

**Comment by molecular** [comment]
@kyuupichan a low-volume mailing list would be great

**Comment by molecular** [comment]
@ser the "peers" rpc command pretty much spits out such a list, no?

**Pull request merged**
