### PR TITLE
Fix payment requests

### LINKED ISSUE #766: payment request fails - payment requests are not working at the moment
Payload to send to Electrum:

```{'params': {'amount': 0.0021651117760957575, 'expiration': 1212}, 'method': 'addrequest', 'id': 'c6cf406e-0c4b-4eb7-b3d2-1712a4d3a553'}```

Data received back from Electrum:

```{'error': {'message': 'Invalid parameters: string argument without an encoding', 'code': -32602}, 'result': None, 'id': '2fd03026-d1ba-49c0-b781-dd30ee758c8d'}```

This but looks similar to https://github.com/spesmilo/electrum/issues/3411 but it is not that simple, as with that patch electron-cash says:

```{'error': {'message': 'Invalid parameters: b\'\\xfc\\\'w|.W\\xeb\\xd5\\xa3u\\x8a\\xc3\\x81v\\x91\\x7f\\x9c"\\xa7\\xd1\' is not JSON serializable', 'code': -32602}, 'result': None, 'id': '9e20dac3-52ac-4ace-b2c2-51f5cf2087b6'}```

It looks roots of this issue are much deeper, unfortunately.

### PR DESCRIPTION
**Pull request by marceloneil**
Fixes #766 

A few commits here:
* Read files as utf-8. Not directly related but I merged the cherry-pick so may as well
* Fix `lib/pem.py`
* Change setconfig to correctly write url_rewrite to config
* Store address as a string when writing payment request files

### CODE REVIEW

**Comment by marceloneil** [comment]
@rt121212121 you said there were side-effects for 8f8eef91b207dfcb538a9edd3eb29f9f17d02f9f, did you mean the additional error that @ser mentioned in #766 or something else?

**Comment by fyookball** [comment]
Looks fine to me.

**Comment by marceloneil** [comment]
It would be good to have a functioning merchant add-on. Thanks @ser for considering BCH, sorry it's been such a struggle.

**Comment by rt121212121** [comment]
The original error ser mentioned.  I made a mistake in merging it due to confusion between comments on different issues.  I didn't put too much time to looking into it, since you'd already started.  The fixes look fine to me, and I expect they work great.  Good work.

**Comment by marceloneil** [comment]
I rebased to fix the commit messages.

The cherry-picks seem fine IMO, and my change does make two assumptions:
* The request file is never read back into the instance of EC that "created" it (couldn't find anything), and customers that use the file (who might be using EC) are expecting an address string. https://github.com/fyookball/electrum/pull/786/commits/233f24b64af9bf8e828825d3c8a9a9b8e425a206#diff-9a32635d4a93b6e41c91fec9e4001d4aR1388
* `add_payment_request` does not need to return the payment request. I searched in the codebase and couldn't find an instance of the return value being used. https://github.com/fyookball/electrum/pull/786/commits/233f24b64af9bf8e828825d3c8a9a9b8e425a206#diff-9a32635d4a93b6e41c91fec9e4001d4aL1390

**Pull request merged**
