### PR TITLE
Use electrumx checkpoints to remove need for pre-checkpoint blockchain sync

### PR DESCRIPTION
**Pull request by rt121212121**
This pull request uses electrumx checkpoints to remove need for pre-checkpoint blockchain sync.  It includes various changes from Electrum adapted for the different checkpoint model.

It comes with recent checkpoint heights and merkle roots included for both testnet and mainnet.  If these are removed (edit `networks.py` and replace the height with None) instead of expecting that height/root, it will fetch at least 3 sets of verification data for the same height from different servers, and won't pass verification stage unless all three match.  The root and height will be printed to the console before it proceeds to use the given header data.

### CODE REVIEW

**Comment by cculianu** [comment]
Wow, good work! This is quite comprehensive! I'm actually busy preparing for my vacation/trip (I won't be around for a while). 

Quick, dumb question (that I probably could answer myself from reading code): Does this still do the "old thing" if connected to an older protocol server? Or are we all pushing to get all the ElectrumX servers compatible with the new protocol changes?

**Comment by kyuupichan** [comment]
@cculianu there are enough servers supporting the new protocol it doesn't matter about stragglers; they serve a purpose in handling old clients...

**Comment by cculianu** [comment]
Very cool. Understood about the protocol and I’m all in favor of moving forward 100% and not worrying about old servers.

@kyuupichan , one final question: does the new server support the old protocol?

Reason I ask is that Apple isn’t allowing me to publish new updates to EC iOS until Jonald and I form a corporation named “Electron Cash”— so it may be September before we get a new iOS update out because bureaucracy involved in that.

Would hate for iOS users to not have a working EC...

**Comment by kyuupichan** [comment]
Yes all protocols back to 1.1 are supported by all servers.  I won't be bumping to 1.2 (which is about 4 months old EC) for another month or so.  I won't be retiring 1.2 until next year

**Comment by cculianu** [comment]
Awesome. This is great work. You spearheaded it kyuupichan and @rt121212121 did great.

Haven’t tested it yet as I’m busy packing but if we get subtle bugs or anything we’ll fix em.

Very exciting! Thanks guys!!! This makes everyone’s life easier especially iOS and j2me!!

**Pull request merged**
