### PR TITLE
Build script fixes

### LINKED ISSUE #332: No packages directory in ElectronCash-3.0.tar.gz
...which is inconsistent with the README.rst file

"If you downloaded the official package (tar.gz), you can run
Electron Cash from its root directory (called Electrum), without installing it on your
system; all the python dependencies are included in the 'packages'
directory."

And obviously I get problems running it "from source" too.

### PR DESCRIPTION
**Pull request by marceloneil**
Fixes #332 

This is kind of the first step in fixing the build scripts.

* Fixes issue where `packages/` directory wasn't in the project root
* Update `freeze_packages.sh` to work with Electron Cash (it doesn't seem like upstream is using it, but it also seems a bit useful)
* Remove `make_download` since it was designed for [electrum.org](https://electrum.org/#home) (so clearly nobody was using it)
* Add `make_compressed` script to build zip/gzip packages more easily

@fyookball

### CODE REVIEW

**Comment by bauerj** [comment]
> Update freeze_packages.sh to work with Electron Cash (it doesn't seem like upstream is using it, but it also seems a bit useful)

We are using it for deterministic builds 😊

**Comment by marceloneil** [comment]
@bauerj How often do you use it, it seems like `requirements.txt` hasn't been updated in a while.

**Comment by bauerj** [comment]
We usually update it before we do a new release.

**Comment by marceloneil** [comment]
That makes sense, although I guess you didn't do one for the RPC fixes

**Pull request merged**
