### PR TITLE
Fix for #770

### PR DESCRIPTION
**Pull request by cculianu**
Turns out the paymentrequest class returns bytes sometimes when you str() it. Fixed the exception triggered as a result.

### CODE REVIEW

**Comment by marceloneil** [comment]
Why are there hundreds of commits haha, you should clean up your local branch

**Comment by marceloneil** [comment]
Also you can just commit directly, no need to create a PR and merge it as long as there is a good description 🙂

**Comment by marceloneil** [comment]
Thanks for the quick fix!

**Comment by cculianu** [comment]
Yeah I wasn't expecting the thousand-commits.  No worries.. got squashed anyway.

Ok -- for quick fixes I'll commit directly.

Yeah my local branch is out of sync commit-wise with master (due to a previous squash).

I am not sure what to do.  I like my version history but I may have to just fork again off of electron cash master.

Next time I do a PR or a direct commit I'll be sure not to have this problem. :)

Yeah thank you for running Professor Venkman!

**Pull request merged**
