### PR TITLE
Refactor module layout

### PR DESCRIPTION
**Pull request by Danconnolly**
rename lib -> electroncash
move gui -> electroncash.gui
move plugins -> electroncash.plugins
fix all imports, remove module manipulations

### CODE REVIEW

**Comment by Danconnolly** [comment]
Note that there is another pull request which changes module names: https://github.com/fyookball/electrum/pull/179

Electrum used lib, gui, and plugins modules and imported them as electrum, electrum_gui, and plugins respectively. Some config in the setup and packaging to handle it also. I'm not sure why it was done this way. Some possible reasons: historical, enable creating distributions without the gui or plugins code.

Anyway, I prefer this solution, I think it makes for a cleaner structure.

**Comment by kenman345** [comment]
Note, this fixes #180

**Comment by Danconnolly** [comment]
This PR will cause issues with other PR's currently submitted. Probably best to merge those if desired before this one. I'm happy to rebase this off a newer cash branch if needed.

**Comment by fyookball** [comment]
im having a look.

**Comment by kyuupichan** [comment]
Any reason some names went to electron and some to electroncash?

**Comment by Danconnolly** [comment]
Closing this PR. I will rebase, reorganise, and resubmit as a new PR.

**Comment by Danconnolly** [comment]
Reopening for visibility, but needs to be re-done

**Pull request closed without merging**
