### PR TITLE
Fix `setup.py` argument parsing for real

### PR DESCRIPTION
**Pull request by alexander255**
Improved version of the reverted commit from #625.

### CODE REVIEW

**Comment by marceloneil** [comment]
This still creates stuff in `~/.local` :disappointed:

**Comment by marceloneil** [comment]
I understand that, but a root installation of electron-cash is still necessary. If `/usr/share` doesn't exist on the system where this is run (which is true when building a package in a chrooted environment, or something similar), it will write to `~/.local`. [Here](https://github.com/fyookball/electrum/pull/655/files#diff-2eeaed663bd0d25b7e608891384b7298R36) `or` should be `and` I think, and that might resolve this issue.

**Comment by alexander255** [comment]
Yeah, that logic statement was still broken :worried: 

The `or` needed to be an `and` *and* the second statement needed to be inverted. I needed to write it out as a multi-line `if` statement and apply logic transformations to achieve the current result. It makes sense but it's terribly non-obvious imho.

**Comment by marceloneil** [comment]
This seems good, and works for me, but I'm going to have the fedora package maintainer test it out first

**Comment by alexander255** [comment]
@rt121212121: I changed it to a three-part `if`-statement where the first two cases `pass` with a comment explaining why.

**Comment by marceloneil** [comment]
Still going to try to get the fedora packager to test the changes, I'll re-test the new commit

**Comment by alexander255** [comment]
@marceloneil: Where you able to check this commit yet?

**Pull request merged**
